# -------------------------------------------------------------------
# GitLab CI/CD recipe for the elliptical-distribution-toolkit package
# -------------------------------------------------------------------

# build off of miniconda3
image: continuumio/miniconda3

# add relevant packages
before_script:
  - conda update -n base -c defaults conda
  - conda install --yes --show-channel-urls coverage flake8 numpy
  - pip install -e .  # Install package in development mode

# call out pipeline stages
stages:
  - test_and_cov

# test and run coverage on the repo source code
# note: GitLab test-coverage-parsing regex is '^TOTAL(\s+\d+)*(\s)+(\d+\%)$',
#       which simply picks the COV% value from the coverage report.
# note: `discover` requires tests/ to be importable as a package, therefore
#       __init__.py files are included along that tree.
test_and_cov_src:
  stage: test_and_cov
  coverage: '/TOTAL.*\s+(\d+%)$/'
  script:
    - python -m unittest discover -v
    - coverage run --source=src --branch -m unittest && coverage report -m

