# -------------------------------------------------------------------
# GitLab CI/CD recipe for the irides package
# -------------------------------------------------------------------

# build off of miniconda3
image: continuumio/miniconda3

# add relevant packages
default:
  before_script:
    - conda update -n base -c defaults conda
    - conda install --yes --show-channel-urls coverage flake8 numpy
    - pip install -e .  # Install package in development mode

# define variables
variables:
  SECRET_DETECTION_ENABLED: 'true'

# call out pipeline stages
stages:
  - test_and_cov
  - secret-detection

# test and run coverage on the repo source code
test_and_cov_src:
  stage: test_and_cov
  coverage: '/TOTAL.*\s+(\d+%)$/'
  script:
    - python -m unittest discover -v
    - coverage run --source=src --branch -m unittest && coverage report -m

# override defaults for the secret detection job
secret_detection:
  stage: secret-detection
  before_script: []  # Prevent conda-related setup
  image: registry.gitlab.com/security-products/secrets:7

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
